export enum OfficeNameEnum {
  OfficeOfTheProvincialGovernor = 0,
  OfficeOfTheProvincialViceGovernor = 1,
  OfficeOfTheProvincialAdministrator = 2,
  OpgRoadSafetyDivision = 3,
  BidsAndAwardsCommitteeB = 4,
  BidsAndAwardsCommitteeA = 5,
  CaviteProvincialJail = 6,
  OpgOfficeOfTheProvincialYouthDevelopmentOfficer = 7,
  OfficeOfTheProvincialHealthOfficer = 8,
  LocalEconomicDevelopmentAndInvestmentPromotionsOffice = 9,
  CaviteCenterForMentalHealth = 10,
  CaviteQualityManagementOffice = 11,
  OfficeOfTheSangguniangPanlalawigan = 12,
  OpgOfficeOfTheProvincialInternalAuditServices = 13,
  ProvincialInformationAndCommunicationsTechnologyOffice = 14,
  OfficeOfTheProvincialEnvironmentAndNaturalResourcesOfficer = 15,
  OfficeOfTheProvincialDisasterRiskReductionAndManagementOfficer = 16,
  PgCaviteOfficeOfPublicSafety = 17,
  OfficeOfTheProvincialEngineer = 18,
  OfficeOfTheProvincialVeterinarian = 19,
  OfficeOfTheProvincialSocialWelfareAndDevelopmentOfficer = 20,
  OfficeOfTheProvincialAgriculturist = 21,
  OfficeOfTheProvincialPopulationOfficer = 22,
  OfficeOfTheProvincialAssessor = 23,
  OfficeOfTheProvincialTreasurer = 24,
  OfficeOfTheProvincialAccountant = 25,
  OfficeOfTheProvincialBudgetOfficer = 26,
  OfficeOfTheProvincialGeneralServicesOfficer = 27,
  OfficeOfTheProvincialLegalOfficer = 28,
  OpgOfficeOfTheProvincialPersonsWithDisabilityAffairsOfficer = 29,
  OfficeOfTheProvincialPlanningAndDevelopmentCoordinator = 30,
  OfficeOfTheProvincialInformationOfficer = 31,
  OfficeOfTheProvincialTourismOfficer = 32,
  OfficeOfTheProvincialCooperativesDevelopmentOfficer = 33,
  OfficeOfTheProvincialPublicEmploymentServiceManager = 34,
  ProvincialHousingAndDevelopmentManagementOffice = 35,
  OfficeOfTheProvincialHumanResourceManagementOfficer = 36
}

export const OfficeNameLabels: Record<OfficeNameEnum, string> = {
  [OfficeNameEnum.OfficeOfTheProvincialGovernor]: "Office of the Provincial Governor",
  [OfficeNameEnum.OfficeOfTheProvincialViceGovernor]: "Office of the Provincial Vice Governor",
  [OfficeNameEnum.OfficeOfTheProvincialAdministrator]: "Office of the Provincial Administrator",
  [OfficeNameEnum.OpgRoadSafetyDivision]: "OPG-Road Safety Division",
  [OfficeNameEnum.BidsAndAwardsCommitteeB]: "Bids and Awards Committee - B",
  [OfficeNameEnum.BidsAndAwardsCommitteeA]: "Bids and Awards Committee - A",
  [OfficeNameEnum.CaviteProvincialJail]: "Cavite Provincial Jail",
  [OfficeNameEnum.OpgOfficeOfTheProvincialYouthDevelopmentOfficer]: "OPG-Office of the Provincial Youth Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialHealthOfficer]: "Office of the Provincial Health Officer",
  [OfficeNameEnum.LocalEconomicDevelopmentAndInvestmentPromotionsOffice]: "Local Economic Development and Investment Promotions Office",
  [OfficeNameEnum.CaviteCenterForMentalHealth]: "Cavite Center for Mental Health",
  [OfficeNameEnum.CaviteQualityManagementOffice]: "Cavite Quality Management Office",
  [OfficeNameEnum.OfficeOfTheSangguniangPanlalawigan]: "Office of the Sangguniang Panlalawigan",
  [OfficeNameEnum.OpgOfficeOfTheProvincialInternalAuditServices]: "OPG-Office of the Provincial Internal Audit Services",
  [OfficeNameEnum.ProvincialInformationAndCommunicationsTechnologyOffice]: "Provincial Information and Communications Technology Office",
  [OfficeNameEnum.OfficeOfTheProvincialEnvironmentAndNaturalResourcesOfficer]: "Office of the Provincial Environment and Natural Resources Officer",
  [OfficeNameEnum.OfficeOfTheProvincialDisasterRiskReductionAndManagementOfficer]: "Office of the Provincial Disaster Risk Reduction and Management Officer",
  [OfficeNameEnum.PgCaviteOfficeOfPublicSafety]: "PG-Cavite Office of Public Safety",
  [OfficeNameEnum.OfficeOfTheProvincialEngineer]: "Office of the Provincial Engineer",
  [OfficeNameEnum.OfficeOfTheProvincialVeterinarian]: "Office of the Provincial Veterinarian",
  [OfficeNameEnum.OfficeOfTheProvincialSocialWelfareAndDevelopmentOfficer]: "Office of the Provincial Social Welfare and Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialAgriculturist]: "Office of the Provincial Agriculturist",
  [OfficeNameEnum.OfficeOfTheProvincialPopulationOfficer]: "Office of the Provincial Population Officer",
  [OfficeNameEnum.OfficeOfTheProvincialAssessor]: "Office of the Provincial Assessor",
  [OfficeNameEnum.OfficeOfTheProvincialTreasurer]: "Office of the Provincial Treasurer",
  [OfficeNameEnum.OfficeOfTheProvincialAccountant]: "Office of the Provincial Accountant",
  [OfficeNameEnum.OfficeOfTheProvincialBudgetOfficer]: "Office of the Provincial Budget Officer",
  [OfficeNameEnum.OfficeOfTheProvincialGeneralServicesOfficer]: "Office of the Provincial General Services Officer",
  [OfficeNameEnum.OfficeOfTheProvincialLegalOfficer]: "Office of the Provincial Legal Officer",
  [OfficeNameEnum.OpgOfficeOfTheProvincialPersonsWithDisabilityAffairsOfficer]: "OPG-Office of the Provincial Persons with Disability Affairs Officer",
  [OfficeNameEnum.OfficeOfTheProvincialPlanningAndDevelopmentCoordinator]: "Office of the Provincial Planning and Development Coordinator",
  [OfficeNameEnum.OfficeOfTheProvincialInformationOfficer]: "Office of the Provincial Information Officer",
  [OfficeNameEnum.OfficeOfTheProvincialTourismOfficer]: "Office of the Provincial Tourism Officer",
  [OfficeNameEnum.OfficeOfTheProvincialCooperativesDevelopmentOfficer]: "Office of the Provincial Cooperatives Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialPublicEmploymentServiceManager]: "Office of the Provincial Public Employment Service Manager",
  [OfficeNameEnum.ProvincialHousingAndDevelopmentManagementOffice]: "Provincial Housing and Development Management Office",
  [OfficeNameEnum.OfficeOfTheProvincialHumanResourceManagementOfficer]: "Office of the Provincial Human Resource Management Officer"
};

export const OfficesArray = Object.keys(OfficeNameEnum)
  .filter((key) => isNaN(Number(key)))
  .map((key) => ({
    value: OfficeNameEnum[key as keyof typeof OfficeNameEnum] as number,
    label: OfficeNameLabels[OfficeNameEnum[key as keyof typeof OfficeNameEnum] as OfficeNameEnum]
  }));