import type { SelectItem } from "@nuxt/ui";

export enum OfficeNameEnum {
  OfficeOfTheProvincialGovernor,
  OfficeOfTheProvincialViceGovernor ,
  OfficeOfTheProvincialAdministrator ,
  OpgRoadSafetyDivision ,
  BidsAndAwardsCommitteeB,
  BidsAndAwardsCommitteeA ,
  CaviteProvincialJail ,
  OpgOfficeOfTheProvincialYouthDevelopmentOfficer,
  OfficeOfTheProvincialHealthOfficer,
  LocalEconomicDevelopmentAndInvestmentPromotionsOffice,
  CaviteCenterForMentalHealth,
  CaviteQualityManagementOffice,
  OfficeOfTheSangguniangPanlalawigan,
  OpgOfficeOfTheProvincialInternalAuditServices,
  ProvincialInformationAndCommunicationsTechnologyOffice,
  OfficeOfTheProvincialEnvironmentAndNaturalResourcesOfficer,
  OfficeOfTheProvincialDisasterRiskReductionAndManagementOfficer,
  PgCaviteOfficeOfPublicSafety ,
  OfficeOfTheProvincialEngineer ,
  OfficeOfTheProvincialVeterinarian ,
  OfficeOfTheProvincialSocialWelfareAndDevelopmentOfficer,
  OfficeOfTheProvincialAgriculturist ,
  OfficeOfTheProvincialPopulationOfficer,
  OfficeOfTheProvincialAssessor,
  OfficeOfTheProvincialTreasurer,
  OfficeOfTheProvincialAccountant,
  OfficeOfTheProvincialBudgetOfficer,
  OfficeOfTheProvincialGeneralServicesOfficer,
  OfficeOfTheProvincialLegalOfficer,
  OpgOfficeOfTheProvincialPersonsWithDisabilityAffairsOfficer,
  OfficeOfTheProvincialPlanningAndDevelopmentCoordinator,
  OfficeOfTheProvincialInformationOfficer,
  OfficeOfTheProvincialTourismOfficer,
  OfficeOfTheProvincialCooperativesDevelopmentOfficer,
  OfficeOfTheProvincialPublicEmploymentServiceManager,
  ProvincialHousingAndDevelopmentManagementOffice,
  OfficeOfTheProvincialHumanResourceManagementOfficer,
}

export const Labels: Record<OfficeNameEnum, string> = {
  [OfficeNameEnum.OfficeOfTheProvincialGovernor]: "Office of the Provincial Governor",
  [OfficeNameEnum.OfficeOfTheProvincialViceGovernor]: "Office of the Provincial Vice Governor",
  [OfficeNameEnum.OfficeOfTheProvincialAdministrator]: "Office of the Provincial Administrator",
  [OfficeNameEnum.OpgRoadSafetyDivision]: "OPG Road Safety Division",
  [OfficeNameEnum.BidsAndAwardsCommitteeB]: "Bids and Awards Committee B",
  [OfficeNameEnum.BidsAndAwardsCommitteeA]: "Bids and Awards Committee A",
  [OfficeNameEnum.CaviteProvincialJail]: "Cavite Provincial Jail",
  [OfficeNameEnum.OpgOfficeOfTheProvincialYouthDevelopmentOfficer]: "OPG Office of the Provincial Youth Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialHealthOfficer]: "Office of the Provincial Health Officer",
  [OfficeNameEnum.LocalEconomicDevelopmentAndInvestmentPromotionsOffice]: "Local Economic Development and Investment Promotions Office",
  [OfficeNameEnum.CaviteCenterForMentalHealth]: "Cavite Center for Mental Health",
  [OfficeNameEnum.CaviteQualityManagementOffice]: "Cavite Quality Management Office",
  [OfficeNameEnum.OfficeOfTheSangguniangPanlalawigan]: "Office of the Sangguniang Panlalawigan",
  [OfficeNameEnum.OpgOfficeOfTheProvincialInternalAuditServices]: "OPG Office of the Provincial Internal Audit Services",
  [OfficeNameEnum.ProvincialInformationAndCommunicationsTechnologyOffice]: "Provincial Information and Communications Technology Office",
  [OfficeNameEnum.OfficeOfTheProvincialEnvironmentAndNaturalResourcesOfficer]: "Office of the Provincial Environment and Natural Resources Officer",
  [OfficeNameEnum.OfficeOfTheProvincialDisasterRiskReductionAndManagementOfficer]: "Office of the Provincial Disaster Risk Reduction and Management Officer",
  [OfficeNameEnum.PgCaviteOfficeOfPublicSafety]: "PG Cavite Office of Public Safety",
  [OfficeNameEnum.OfficeOfTheProvincialEngineer]: "Office of the Provincial Engineer",
  [OfficeNameEnum.OfficeOfTheProvincialVeterinarian]: "Office of the Provincial Veterinarian",
  [OfficeNameEnum.OfficeOfTheProvincialSocialWelfareAndDevelopmentOfficer]: "Office of the Provincial Social Welfare and Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialAgriculturist]: "Office of the Provincial Agriculturist",
  [OfficeNameEnum.OfficeOfTheProvincialPopulationOfficer]: "Office of the Provincial Population Officer",
  [OfficeNameEnum.OfficeOfTheProvincialAssessor]: "Office of the Provincial Assessor",
  [OfficeNameEnum.OfficeOfTheProvincialTreasurer]: "Office of the Provincial Treasurer",
  [OfficeNameEnum.OfficeOfTheProvincialAccountant]: "Office of the Provincial Accountant",
  [OfficeNameEnum.OfficeOfTheProvincialBudgetOfficer]: "Office of the Provincial Budget Officer",
  [OfficeNameEnum.OfficeOfTheProvincialGeneralServicesOfficer]: "Office of the Provincial General Services Officer",
  [OfficeNameEnum.OfficeOfTheProvincialLegalOfficer]: "Office of the Provincial Legal Officer",
  [OfficeNameEnum.OpgOfficeOfTheProvincialPersonsWithDisabilityAffairsOfficer]: "OPG Office of the Provincial Persons with Disability Affairs Officer",
  [OfficeNameEnum.OfficeOfTheProvincialPlanningAndDevelopmentCoordinator]: "Office of the Provincial Planning and Development Coordinator",
  [OfficeNameEnum.OfficeOfTheProvincialInformationOfficer]: "Office of the Provincial Information Officer",
  [OfficeNameEnum.OfficeOfTheProvincialTourismOfficer]: "Office of the Provincial Tourism Officer",
  [OfficeNameEnum.OfficeOfTheProvincialCooperativesDevelopmentOfficer]: "Office of the Provincial Cooperatives Development Officer",
  [OfficeNameEnum.OfficeOfTheProvincialPublicEmploymentServiceManager]: "Office of the Provincial Public Employment Service Manager",
  [OfficeNameEnum.ProvincialHousingAndDevelopmentManagementOffice]: "Provincial Housing and Development Management Office",
  [OfficeNameEnum.OfficeOfTheProvincialHumanResourceManagementOfficer]: "Office of the Provincial Human Resource Management Officer",
};

export function getLabel(office: OfficeNameEnum): string {
  return Labels[office] ?? office;
}

export const OfficeOptions:SelectItem[] = [
  { label: "Office of the Provincial Governor", value: OfficeNameEnum.OfficeOfTheProvincialGovernor },
  { label: "Office of the Provincial Vice Governor", value: OfficeNameEnum.OfficeOfTheProvincialViceGovernor },
  { label: "Office of the Provincial Administrator", value: OfficeNameEnum.OfficeOfTheProvincialAdministrator },
  { label: "OPG Road Safety Division", value: OfficeNameEnum.OpgRoadSafetyDivision },
  { label: "Bids and Awards Committee B", value: OfficeNameEnum.BidsAndAwardsCommitteeB },
  { label: "Bids and Awards Committee A", value: OfficeNameEnum.BidsAndAwardsCommitteeA },
  { label: "Cavite Provincial Jail", value: OfficeNameEnum.CaviteProvincialJail },
  { label: "OPG Office of the Provincial Youth Development Officer", value: OfficeNameEnum.OpgOfficeOfTheProvincialYouthDevelopmentOfficer },
  { label: "Office of the Provincial Health Officer", value: OfficeNameEnum.OfficeOfTheProvincialHealthOfficer },
  { label: "Local Economic Development and Investment Promotions Office", value: OfficeNameEnum.LocalEconomicDevelopmentAndInvestmentPromotionsOffice },
  { label: "Cavite Center for Mental Health", value: OfficeNameEnum.CaviteCenterForMentalHealth },
  { label: "Cavite Quality Management Office", value: OfficeNameEnum.CaviteQualityManagementOffice },
  { label: "Office of the Sangguniang Panlalawigan", value: OfficeNameEnum.OfficeOfTheSangguniangPanlalawigan },
  { label: "OPG Office of the Provincial Internal Audit Services", value: OfficeNameEnum.OpgOfficeOfTheProvincialInternalAuditServices },
  { label: "Provincial Information and Communications Technology Office", value: OfficeNameEnum.ProvincialInformationAndCommunicationsTechnologyOffice },
  { label: "Office of the Provincial Environment and Natural Resources Officer", value: OfficeNameEnum.OfficeOfTheProvincialEnvironmentAndNaturalResourcesOfficer },
  { label: "Office of the Provincial Disaster Risk Reduction and Management Officer", value: OfficeNameEnum.OfficeOfTheProvincialDisasterRiskReductionAndManagementOfficer },
  { label: "PG Cavite Office of Public Safety", value: OfficeNameEnum.PgCaviteOfficeOfPublicSafety },
  { label: "Office of the Provincial Engineer", value: OfficeNameEnum.OfficeOfTheProvincialEngineer },
  { label: "Office of the Provincial Veterinarian", value: OfficeNameEnum.OfficeOfTheProvincialVeterinarian },
  { label: "Office of the Provincial Social Welfare and Development Officer", value: OfficeNameEnum.OfficeOfTheProvincialSocialWelfareAndDevelopmentOfficer },
  { label: "Office of the Provincial Agriculturist", value: OfficeNameEnum.OfficeOfTheProvincialAgriculturist },
  { label: "Office of the Provincial Population Officer", value: OfficeNameEnum.OfficeOfTheProvincialPopulationOfficer },
  { label: "Office of the Provincial Assessor", value: OfficeNameEnum.OfficeOfTheProvincialAssessor },
  { label: "Office of the Provincial Treasurer", value: OfficeNameEnum.OfficeOfTheProvincialTreasurer },
  { label: "Office of the Provincial Accountant", value: OfficeNameEnum.OfficeOfTheProvincialAccountant },
  { label: "Office of the Provincial Budget Officer", value: OfficeNameEnum.OfficeOfTheProvincialBudgetOfficer },
  { label: "Office of the Provincial General Services Officer", value: OfficeNameEnum.OfficeOfTheProvincialGeneralServicesOfficer },
  { label: "Office of the Provincial Legal Officer", value: OfficeNameEnum.OfficeOfTheProvincialLegalOfficer },
  { label: "OPG Office of the Provincial Persons with Disability Affairs Officer", value: OfficeNameEnum.OpgOfficeOfTheProvincialPersonsWithDisabilityAffairsOfficer },
  { label: "Office of the Provincial Planning and Development Coordinator", value: OfficeNameEnum.OfficeOfTheProvincialPlanningAndDevelopmentCoordinator },
  { label: "Office of the Provincial Information Officer", value: OfficeNameEnum.OfficeOfTheProvincialInformationOfficer },
  { label: "Office of the Provincial Tourism Officer", value: OfficeNameEnum.OfficeOfTheProvincialTourismOfficer },
  { label: "Office of the Provincial Cooperatives Development Officer", value: OfficeNameEnum.OfficeOfTheProvincialCooperativesDevelopmentOfficer },
  { label: "Office of the Provincial Public Employment Service Manager", value: OfficeNameEnum.OfficeOfTheProvincialPublicEmploymentServiceManager },
  { label: "Provincial Housing and Development Management Office", value: OfficeNameEnum.ProvincialHousingAndDevelopmentManagementOffice },
  { label: "Office of the Provincial Human Resource Management Officer", value: OfficeNameEnum.OfficeOfTheProvincialHumanResourceManagementOfficer },
];