<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.6.0" />
   
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.3" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Application\AssignAndApprove\" />
    <Folder Include="Features\Application\Delete\" />
    <Folder Include="Features\Application\GetById\" />
    <Folder Include="Features\Application\SoftDelete\" />
    <Folder Include="Features\Application\Update\" />
    <Folder Include="Features\Endorsement\" />
    <Folder Include="Features\Endorsement\Create\" />
    <Folder Include="Features\Endorsement\Preview\" />
    <Folder Include="Features\Endorsement\Shared\" />
  </ItemGroup>

</Project>
